module tb_testing;

parameter clk_cycle=10;
reg clk;
reg [7:0] thresh;
reg [7:0] pixelIn;
reg [] theOutput;

mySobel #(,) sobel(
	.clk(clock),
	.threshold(thresh),
	.pixel(pixelIn), 
	.bmpOutput(theOutput) 

);







endmodule